# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserQuery(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, query: str=None, lang: str=None, user_id: str=None, passwd: str=None):  # noqa: E501
        """UserQuery - a model defined in Swagger

        :param query: The query of this UserQuery.  # noqa: E501
        :type query: str
        :param lang: The lang of this UserQuery.  # noqa: E501
        :type lang: str
        :param user_id: The user_id of this UserQuery.  # noqa: E501
        :type user_id: str
        :param passwd: The passwd of this UserQuery.  # noqa: E501
        :type passwd: str
        """
        self.swagger_types = {
            'query': str,
            'lang': str,
            'user_id': str,
            'passwd': str
        }

        self.attribute_map = {
            'query': 'query',
            'lang': 'lang',
            'user_id': 'user_id',
            'passwd': 'passwd'
        }
        self._query = query
        self._lang = lang
        self._user_id = user_id
        self._passwd = passwd

    @classmethod
    def from_dict(cls, dikt) -> 'UserQuery':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserQuery of this UserQuery.  # noqa: E501
        :rtype: UserQuery
        """
        return util.deserialize_model(dikt, cls)

    @property
    def query(self) -> str:
        """Gets the query of this UserQuery.


        :return: The query of this UserQuery.
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query: str):
        """Sets the query of this UserQuery.


        :param query: The query of this UserQuery.
        :type query: str
        """
        if query is None:
            raise ValueError("Invalid value for `query`, must not be `None`")  # noqa: E501

        self._query = query

    @property
    def lang(self) -> str:
        """Gets the lang of this UserQuery.


        :return: The lang of this UserQuery.
        :rtype: str
        """
        return self._lang

    @lang.setter
    def lang(self, lang: str):
        """Sets the lang of this UserQuery.


        :param lang: The lang of this UserQuery.
        :type lang: str
        """
        if lang is None:
            raise ValueError("Invalid value for `lang`, must not be `None`")  # noqa: E501

        self._lang = lang

    @property
    def user_id(self) -> str:
        """Gets the user_id of this UserQuery.


        :return: The user_id of this UserQuery.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this UserQuery.


        :param user_id: The user_id of this UserQuery.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def passwd(self) -> str:
        """Gets the passwd of this UserQuery.


        :return: The passwd of this UserQuery.
        :rtype: str
        """
        return self._passwd

    @passwd.setter
    def passwd(self, passwd: str):
        """Sets the passwd of this UserQuery.


        :param passwd: The passwd of this UserQuery.
        :type passwd: str
        """
        if passwd is None:
            raise ValueError("Invalid value for `passwd`, must not be `None`")  # noqa: E501

        self._passwd = passwd
