openapi: 3.0.0
info:
  title: Custormer API
  description: This is a simple User API by GROUP 3.
  version: 0.2.3
servers:
- url: /
tags:
- name: User
  description: Operations about Users
paths:
  /User:
    get:
      tags:
      - User
      summary: Get Users
      description: 'Get all Users from the DB '
      operationId: get_all_users
      responses:
        "200":
          description: OK
        "404":
          description: Not found
      x-swagger-router-controller: swagger_server.controllers.user_controller
      x-openapi-router-controller: swagger_server.controllers.user_controller
    post:
      tags:
      - User
      summary: Creates a customer.
      operationId: create_user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "201":
          description: Successful created
        "409":
          description: User already exists
      x-swagger-router-controller: swagger_server.controllers.user_controller
      x-openapi-router-controller: swagger_server.controllers.user_controller
  /User/{id}:
    put:
      tags:
      - User
      summary: Modify user
      description: 'To modify a a username/Password '
      operationId: modify_user
      parameters:
      - name: id
        in: path
        description: The ID of the customer to delete.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserModi'
        required: true
      responses:
        "200":
          description: updated successfully
        "204":
          description: 'No content '
        "404":
          description: 'UserName not found '
      x-swagger-router-controller: swagger_server.controllers.user_modi_controller
      x-openapi-router-controller: swagger_server.controllers.user_controller
    delete:
      tags:
      - User
      summary: Delete user
      description: To delete a user entry
      operationId: delete_user
      parameters:
      - name: id
        in: path
        description: The username of the user that needs to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Deleted sucessfully
        "404":
          description: User not found
      x-swagger-router-controller: swagger_server.controllers.user_controller
      x-openapi-router-controller: swagger_server.controllers.user_controller
components:
  schemas:
    User:
      required:
      - id
      - passwd
      type: object
      properties:
        id:
          type: string
        passwd:
          type: string
    UserModi:
      required:
      - Modification
      - Option
      - id
      - passwd
      type: object
      properties:
        id:
          type: string
        passwd:
          type: string
        Option:
          type: integer
        Modification:
          type: string